.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH DARGUI 1 
.SH NAME
dargui \- a gui for 
.BR dar (1)
.SH SYNOPSIS
.B dargui [file] 
.SH DESCRIPTION
.B dargui
provides a GUI for Denis Corbin's 
.BR dar(1) 
archiving utility. It allows the user to 
assemble dar command lines and batch files easily, to
create archives and extract files from archives.
.SH OPTIONS
.IP file
the filename of a dar archive to open on starting dargui
.SH BUGS
This is a beta release. Please contact the author at the 
address below, detailing any bugs which you detect.
.SH AUTHOR
Malcolm Poole <mgpoole@users.sourceforge.net>
.SH "SEE ALSO"
.BR dar (1)
